// Category 5: Nepali-calendar (NepaliDate, Bikram Sambat) specific
// functions — 18 functions (#89 through #106).
//
// Range limitation: NepaliDate in persian_calendar only covers dates whose
// Gregorian equivalent falls between 1975 and 2199 (per the package's own
// documentation). Functions in this file that construct a NepaliDate for a
// year outside that range will throw, exactly as the underlying library
// does; this file does not add any extra bounds checking beyond what
// persian_calendar itself provides.
//
// Weekday convention: the Nepali week starts on Sunday (आइतबार), so
// nepaliGetMonthGrid uses the remapping `(canonical + 1) % 7` to map the
// canonical Monday=0 order onto Sunday=0 ... Saturday=6 columns.
//
// "Leap year" caveat: unlike the Gregorian calendar, Bikram Sambat month
// lengths are not generated by a fixed rule; each year's total length is a
// property of the underlying data table. [nepaliIsLeapYear] therefore
// treats "leap" loosely, as "longer than the most common (365-day) year"
// rather than a strict astronomical definition.

import 'package:persian_calendar/persian_calendar.dart';

import '../core/generic.dart';

const List<String> _nepaliMonthNamesNe = [
  'बैशाख', 'जेष्ठ', 'आषाढ', 'श्रावण', 'भाद्र', 'आश्विन', //
  'कार्तिक', 'मंसिर', 'पौष', 'माघ', 'फाल्गुन', 'चैत्र',
];
const List<String> _nepaliMonthNamesEn = [
  'Baisakh', 'Jestha', 'Ashadh', 'Shrawan', 'Bhadra', 'Ashwin', //
  'Kartik', 'Mangsir', 'Poush', 'Magh', 'Falgun', 'Chaitra',
];
// Canonical order (Monday=0 ... Sunday=6)
const List<String> _weekdayNamesNe = [
  'सोमबार', 'मंगलबार', 'बुधबार', 'बिहीबार', 'शुक्रबार', 'शनिबार', //
  'आइतबार',
];
const List<String> _weekdayNamesEn = [
  'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', //
  'Sunday',
];

const Map<String, String> _devanagariDigitsMap = {
  '0': '०', '1': '१', '2': '२', '3': '३', '4': '४', //
  '5': '५', '6': '६', '7': '७', '8': '८', '9': '९',
};

String _toDevanagariDigits(String input) =>
    input.split('').map((c) => _devanagariDigitsMap[c] ?? c).join();

NepaliDate _todayNepali() {
  final now = DateTime.now();
  return NepaliDate.fromDate(CivilDate(now.year, now.month, now.day));
}

/// (89) Numeric display of a Nepali date using Devanagari digits, as
/// YYYY/MM/DD.
///
/// Example: `nepaliToString(NepaliDate(2081, 12, 1))` → `'२०८१/१२/०१'`
String nepaliToString(NepaliDate date) {
  final y = date.year.toString().padLeft(4, '0');
  final m = date.month.toString().padLeft(2, '0');
  final d = date.dayOfMonth.toString().padLeft(2, '0');
  return _toDevanagariDigits('$y/$m/$d');
}

/// (90) Full display of a Nepali date including weekday name and month
/// name, using Devanagari digits.
///
/// Example: `nepaliToFullString(NepaliDate(2081, 12, 1))` →
/// `'सोमबार १ फाल्गुन २०८१'` (the weekday name depends on the actual
/// computed date)
String nepaliToFullString(NepaliDate date) {
  final weekday = nepaliWeekdayName(date);
  final month = nepaliMonthName(date.month);
  final day = _toDevanagariDigits(date.dayOfMonth.toString());
  final year = _toDevanagariDigits(date.year.toString());
  return '$weekday $day $month $year';
}

/// (91) Formats a Nepali date using a custom pattern (Latin digits).
///
/// Tokens: `YYYY`, `YY`, `MMMM` (English month name), `MM`, `M`, `DDDD`
/// (English weekday name), `DD`, `D`.
///
/// Example: `nepaliFormat(NepaliDate(2081, 12, 1), 'DD MMMM YYYY')` →
/// `'01 Falgun 2081'`
String nepaliFormat(NepaliDate date, String pattern) {
  final tokens = <String, String Function()>{
    'YYYY': () => date.year.toString().padLeft(4, '0'),
    'YY': () => (date.year % 100).toString().padLeft(2, '0'),
    'MMMM': () => nepaliMonthNameEn(date.month),
    'MM': () => date.month.toString().padLeft(2, '0'),
    'M': () => date.month.toString(),
    'DDDD': () => nepaliWeekdayNameEn(date),
    'DD': () => date.dayOfMonth.toString().padLeft(2, '0'),
    'D': () => date.dayOfMonth.toString(),
  };
  final orderedKeys = tokens.keys.toList()
    ..sort((a, b) => b.length.compareTo(a.length));
  final regex = RegExp(orderedKeys.map(RegExp.escape).join('|'));
  return pattern.replaceAllMapped(regex, (m) => tokens[m[0]]!());
}

/// (92) Converts a Nepali date to a Persian date.
PersianDate nepaliToPersian(NepaliDate date) => PersianDate.fromDate(date);

/// (93) Converts a Nepali date to a Gregorian date.
CivilDate nepaliToGregorian(NepaliDate date) => CivilDate.fromDate(date);

/// (94) Converts a Nepali date to an Islamic date.
IslamicDate nepaliToIslamic(NepaliDate date) => IslamicDate.fromDate(date);

/// (95) Is the given Nepali year "leap" in the loose sense of being longer
/// than the most common 365-day year? See the file-level note above for why
/// this is not a strict astronomical definition.
///
/// Example: `nepaliIsLeapYear(2081)` → `true` if that year totals 366 days.
bool nepaliIsLeapYear(int year) => nepaliDaysInYear(year) != 365;

/// (96) The Nepali (Devanagari) name of the weekday of a Nepali date.
String nepaliWeekdayName(NepaliDate date) => _weekdayNamesNe[date.toJdn() % 7];

/// (97) The English name of the weekday of a Nepali date.
String nepaliWeekdayNameEn(NepaliDate date) =>
    _weekdayNamesEn[date.toJdn() % 7];

/// (98) The Nepali (Devanagari) name of a Nepali month (1 to 12).
String nepaliMonthName(int month) => _nepaliMonthNamesNe[month - 1];

/// (99) The English (transliterated) name of a Nepali month.
String nepaliMonthNameEn(int month) => _nepaliMonthNamesEn[month - 1];

/// (100) Adds (or subtracts) a number of days to a Nepali date.
NepaliDate nepaliAddDays(NepaliDate date, int days) =>
    NepaliDate.fromJdn(date.toJdn() + days);

/// (101) Adds (or subtracts) a number of months; the day is clamped to the
/// last day of the target month if needed.
NepaliDate nepaliAddMonths(NepaliDate date, int months) {
  final totalMonths = date.year * 12 + (date.month - 1) + months;
  final newYear = (totalMonths - totalMonths % 12) ~/ 12;
  final newMonth = totalMonths % 12 + 1;
  final maxDay = getMonthDays(newYear, newMonth, NepaliDate.new);
  final newDay = date.dayOfMonth > maxDay ? maxDay : date.dayOfMonth;
  return NepaliDate(newYear, newMonth, newDay);
}

/// (102) Adds (or subtracts) a number of years; the day is clamped if
/// needed.
NepaliDate nepaliAddYears(NepaliDate date, int years) {
  final newYear = date.year + years;
  final maxDay = getMonthDays(newYear, date.month, NepaliDate.new);
  final newDay = date.dayOfMonth > maxDay ? maxDay : date.dayOfMonth;
  return NepaliDate(newYear, date.month, newDay);
}

/// (103) The total number of days in a Nepali year.
int nepaliDaysInYear(int year) {
  final thisYearStart = NepaliDate(year, 1, 1).toJdn();
  final nextYearStart = NepaliDate(year + 1, 1, 1).toJdn();
  return nextYearStart - thisYearStart;
}

/// (104) The day-of-year number for a Nepali date.
int nepaliDayOfYear(NepaliDate date) =>
    date.toJdn() - NepaliDate(date.year, 1, 1).toJdn() + 1;

/// (105) Is this date equal to today (based on the system clock)?
bool nepaliIsToday(NepaliDate date) => isSameDay(date, _todayNepali());

/// (106) A 6x7 grid of the days of a Nepali month, for rendering a calendar
/// widget (the week starts on Sunday, the Nepali convention). Cells outside
/// the range of the month are filled with `null`.
List<List<int?>> nepaliGetMonthGrid(int year, int month) {
  final firstDayCanonical = getFirstDayOfMonth(year, month, NepaliDate.new);
  // Map from canonical order (Monday=0) to Nepali order (Sunday=0)
  final firstDaySundayIndexed = (firstDayCanonical + 1) % 7;
  final daysInMonth = getMonthDays(year, month, NepaliDate.new);

  final grid = List.generate(6, (_) => List<int?>.filled(7, null));
  var day = 1;
  for (var week = 0; week < 6 && day <= daysInMonth; week++) {
    for (var col = 0; col < 7; col++) {
      if (week == 0 && col < firstDaySundayIndexed) continue;
      if (day > daysInMonth) continue;
      grid[week][col] = day;
      day++;
    }
  }
  return grid;
}
